language: objective-c
osx_image: xcode8
script:
- xcodebuild clean test -project FuzzySearch.xcodeproj -scheme FuzzySearch -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=9.0,name=iPhone 5' ONLY_ACTIVE_ARCH=NO | xcpretty